### ISSUE TITLE
Better docs for local-volume provisioner

### ISSUE THREAD

**Issue by micw** [elastic/local-volume#5]
## Proposal

The code of local-volume provisioner seems to contain undocumented features which can be very useful. E.g. it contains the "driver-kind" option that allows to use bind-mounts instead of LVM which can be very usefull.
Unfortunately there's no reference in the docs about this feature.

Please add some docs for this (and potentially other undocumented) features.

Kind regards,
Michael.

**Comment by sebgl** [comment]
I'm transferring the issue to the local-volume repository, now moved out of cloud-on-k8s.

**Comment by sebgl** [comment]
We're going to archive this project. Other interesting alternatives exist now. [TopoLVM](https://github.com/cybozu-go/topolvm) for example does support LVM volumes using the CSI interface.
