### ISSUE TITLE
Possibility of relicensing

### ISSUE THREAD

**Issue by ridv** [elastic/local-volume#7]
Apologies for bringing up a topic I'm sure most folks in Elastic are tired of hearing about, but I figured it never hurts to ask.

I'm from PayPal and my team is looking into contributing to this project. Unfortunately, our legal department has determined upon looking at the licensing that we can only use binaries generated by the untouched source code for and only for testing purposes.

With this in mind, would it be at all possible to consider switching to a more permissive license, such as Apache v2, so that we may collaborate with you folks on this project?

**Comment by mbdas** [comment]
To be explicit, does the licensing prohibit us to use this project in production as part of our kubernetes setup in internal infrastructure where we are not competing with elastic? If any changes have  PR's in upstream etc. Basically we are looking at this to see if we can create a private sandbox directory for each pod that gets mounted inside the pod and that survives pod death and garbage collected later though a policy.

**Comment by sebgl** [comment]
Sorry for the delay: we're still discussing this internally. Will come back to you asap.

**Comment by mbdas** [comment]
Very much appreciated!

**Comment by sebgl** [comment]
Hi @ridv @mbdas,

Sorry for the long wait. This project is clearly not actively maintained, we plan to archive it (read-only) so it still stays available on Github but there are no plans currently to improve it.

We suggest you look into other projects, especially [TopoLVM](https://github.com/cybozu-go/topolvm) which achieves similar things, with more features, by implementing Kubernetes CSI interface.
