### ISSUE TITLE
Trying to install (make docker-build-push), but some errors appeared

### ISSUE THREAD

**Issue by Mr-Reca** [elastic/local-volume#8]
Good morning,

I'm trying to deploy an Elasticsearch cluster using ECK on premise. I do not have a StorageClass, so I want to test local-volume.

When I'm trying to install local-volume, it gives me the following output in step 3:

`COPY failed: stat /var/lib/docker/tmp/docker-builder071461132/vendor: no such file or directory`

I realized that there is no `vendor` folder here, so I commented the line and I tried to continue with the installation. It stopped in step 6 (it should be 7, but the 3rd is commented):
```
cmd/driverclient/init.go:11:2: cannot find package "github.com/spf13/cobra" in any of:
        /usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
        /go/src/github.com/spf13/cobra (from $GOPATH)
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=amd64 &&     go build -o bin/driverclient ./cmd/driverclient &&     go build -o bin/driverdaemon ./cmd/driverdaemon &&     go build -o bin/provisioner  ./cmd/provisioner' returned a non-zero code: 1
Makefile:75: recipe for target 'docker-build-push' failed
make: *** [docker-build-push] Error 1

```

**Comment by sebgl** [comment]
You probably need to install dependencies first: `make dep`.

Note this project is not actively maintained anymore. You may want to look at some alternatives [listed there](https://github.com/elastic/local-volume#dynamic-provisioner-for-local-volumes).
